/*

Author: Tushya Iyer
For: BCIT ACIT 4850 Final Exam
Date: December 8th, 2021
Description: Jenkins Pipeline for sample python application
                Stages are Build, Code Quality, Code Quantity,
                Run Scripts, and ZIP

*/

pipeline {
    agent any
    parameters {
        string(defaultValue: "", description: 'Run Target Scripts', name: 'TARGET')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Running The Requirements...'
                sh "pip install -r requirements.txt"
                echo 'Requirements Complete!'
                echo 'NAME: Tushya Iyer'
                echo 'GROUP: 7'
                echo 'STUDENT NUMBER: A01023434'
            }
        }
        stage('Code Quality') {
            steps {
              sh "pylint-fail-under --fail_under 7 *.py"
            }
        }
        stage('Code Quantity') {
            steps {
              sh "wc -l *.py"
            }
        }
        stage('Run Scripts') {
        when {
            expression {
                params.TARGET == 'run'
            }
        }
        steps {
              sh "python3 main.py phone text output"
              sh "python3 main.py phone csv output"
              sh "python3 main.py phone json output"
            }
        }
        stage('Zip') {
            steps {
                sh "zip app.zip *.py"
            }
            post {
                always {
                    archiveArtifacts artifacts: "app.zip"
                }
            }
        }
    }
}
