pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: "", description: 'Run Target Scripts', name: 'TARGET')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Running The Requirements...'
            }
            steps {
                sh "pip install -r ./${buildDir}/requirements.txt"
            }
            steps {
                echo 'Requirements Complete!'
            }
        }
        stage('Code Quality') {
            steps {
              sh "pylint-fail-under --fail_under 7 ../*.py"
            }
        }
        stage('Code Quantity##############################') {
            steps {
              sh "pylint-fail-under --fail_under 7 ../*.py"
            }
        }
        stage('Package') {
            when {
                expression {
                    ${TARGET} == 'run'
                }
            }
            steps {
                withCredentials([string(credentialsId: '5b19aa88-663b-4267-8695-1c88fcf30492', variable: 'TOKEN')]) {
                    sh "docker login -u 'bakedspacetime' -p '$TOKEN' docker.io"
                    sh "docker build -t ${dockerRepoName}:latest --tag bakedspacetime/${dockerRepoName}:${tagName} ./${buildDir}"
                    sh "docker push bakedspacetime/${dockerRepoName}:${tagName}"
                }
            }
        }
        stage('Zip') {
            steps {
                sh "zip app.zip ../*.py"
            }
            post {
                always {
                    archiveArtifacts artifacts: "app.zip"
                }
            }
        }
    }
}
}
